title: Lerntagebuch Bibliotheks- und Archivinformatik
author: caelscure
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2023
 
 
github_username:  caelscure # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
